In [ ]:
#Import Numpy 

In [1]:
import numpy as np

In [ ]:
#Arrays

In [7]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#other way to creating an array

In [9]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(1,2,7)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [15]:
np.array(np.random.randn(5),dtype='int')

array([-2,  0,  0,  0,  0])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.array([1,2,3],dtype='float')

array([1., 2., 3.])